### ISSUE TITLE
Test issue - Liquidity | Clicking on Zap in on MIN assigns LQ to the dropdown instead

### ISSUE THREAD

**Issue by vrsttl** [minswap/issues#1]
Story: user tried to zap in min but on button click the selected token flipped to LQ

Pre-condition: User has non-zero LQ along with many other tokens in wallet. Using CCVault

Steps:
1; navigate to zap
2; select Min to ADA. Add amount 80 Min
3; confirm

Actual: 

![FCEBD9C9-AD7E-4733-BEEF-B55EADAAC2E0](https://user-images.githubusercontent.com/36707938/155005555-d899e5d4-6165-48e3-8c1d-cfcb0e1d454b.jpeg)

Expectation: Should zap in MIN and not LQ

**Comment by spock29** [comment]
Good job
