### ISSUE TITLE
Precalculate available ADA funds, preventing insufficient UTxO balance issues in the frontend

### ISSUE THREAD

**Issue by tsujisalju** [minswap/issues#4]
Issues relating to insufficient UTxO balance is a frequent problem among users. The problem is mainly due to some ADA are required to hold native tokens in the wallet, and therefore not all of them are allowed to be used, among many other issues similar to it.

I propose that we precalculate the amount of ADA that is available for swapping and set it as the maximum during the swap process, instead of using the full amount. We will need to inform the user about it in the wallet balance, or a tooltip during swapping process.

This will help reduce a whole lot of support tickets and complaints on discord, by not allowing the users to use the full ADA amount in the first place.

Looking to assign James to the task, but I'm not sure how to assign team members as an outsider, I believe it can be assigned by the team.

Best regards,
smolpadok

**Comment by changeling** [comment]
I'm currently struggling with this issue. Just adding a yes vote here.

**Comment by tsujisalju** [comment]
For now, the Eternl wallet has a handy new feature that displays the current available ADA funds for transactions, and the amount currently locked to hold native tokens. If we are able access this information or see how it works, we may implement it natively on the interface. At the moment, its a useful indicator to estimate how much ADA you have at hand to interact with Minswap.
