### ISSUE TITLE
Unable to register on MinSwap forum - Activation email is never received

### ISSUE THREAD

**Issue by QCPOLstakepool** [minswap/issues#5]
We both tried to register on the forum and both of us never received the activation email for the forum registration.

We tried with gmail, icloud and personnal domain emails. 

Nothing in the spam folders of all emails.

Thanks,

**Comment by tvtduy59** [comment]
Hi @QCPOLstakepool,
I've just tried on my end and it doesn't happen. Do you still get this issue?

**Comment by longngn** [comment]
this is due to our email service provider limit 100 emails/day for free plan, I'm upgrading it

**Comment by QCPOLstakepool** [comment]
@tvtduy59 @longngn 

I just tried and still no email.

**Comment by longngn** [comment]
Fixed
